# -*- coding: utf-8 -*-
"""plotimage.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VL4TpepjT4csDUhI8Wkqzyb-zESIjIPt
"""



import matplotlib.pyplot as plt
import numpy as np
import torchvision
# functions to show an image


def imshow(img):
    img = img / 2 + 0.5 
    #print(img.shape())    # unnormalize
    npimg = img.numpy()
    
    plt.imshow(np.transpose(npimg, (1, 2, 0)))

def show_random_images(train_loader,classes):
    # get some random training images
    dataiter = iter(train_loader)
    images, labels = dataiter.next()
    #print(images[0].shape())
    # show images
    imshow(torchvision.utils.make_grid(images))
    # print labels
    print(' '.join('%5s' % classes[labels[j]] for j in range(4)))